### PR TITLE
Enhancement - Prevent Retrigger Layout

### LINKED ISSUE #174: Changing node and edge options should not re-trigger layout
# Feature Request

Request from Marton

### Description

Currently, if you change  node and edge options, the layout positions gets re-applied. This is quite an irritating behaviour since most of the time you have already adjusted the positions manually. 

Layout should only change when new data is added or removed, data is filtered or layout is explicitly triggered. Otherwise, for a better user experience, it should remain as it is when other node and edge options are adjusted.

### PR DESCRIPTION
**Pull request by CodesAreHonest**
## PR Type

What kind of change does this PR introduce?

- Enhancements

## Description

- Prevent re-trigger layout after changing values in Node and Edge options for better user experiences.

## Detailed Description

The features that readjust and not retrigger the layout are listed below: 

|Retrigger|Not Retrigger|
|:-:|:-:|
|Import Sample Data|Import Local File|
|Toggle Layout Options|Node/Edge Options|

1. Import Sample Data (Circle, Random + Circle, Banking Connections and Les Miserables) will default the layout to concentric for demonstration and aesthetic purposes. 
2. Data modification (local uploads, time series analysis, removal and deletion) will not change the layout. 
3. Filter data and hide data will break the layout because we did not "remember" the "x" and "y" position of the nodes. 

## Technical Discussion

When user drags the node or canvas, we will change the layout to 'preset' prevent `Graphin` re-trigger the `LayoutController` to `G6`. If user willing to change desired layout, he/she is required to change the layout in the **Layout Option**. 

## Test Plan

Jest and Cypress unable to test the interaction on the G6 drags action, manual test required. 

## Does this PR introduce breaking change?

- No

close #174

### CODE REVIEW

**Comment by CodesAreHonest** [comment]
## TODO 

* [ ] 1. Import data should not re-trigger layout when filter is active
* [ ] 2. Style node and edge should not re-trigger when filter is active

**Comment by CodesAreHonest** [comment]
## Description for Changes

1.  Fix import data should not re-trigger layout when filter is active
2. Fix Style node and edge should not re-trigger when filter is active
3. Convert Activate Relations and Display Tooltip with double clicks to prevent tooltips affect the user experiences of dragging nodes.

**Comment by timlrx** [comment]
Thanks for the fixes. Two remaining issues I noticed:
1) changing to xy-coordinates when moving a node seem to trigger more movement of nodes than expected
2) double-clicking on a node also highlights "Search" in the search panel

https://user-images.githubusercontent.com/28362229/125010395-01380a00-e099-11eb-9ebf-ae5d8a030d8c.mp4

**Comment by CodesAreHonest** [comment]
## TODO 

* [ ] 1. Disable Click Select behaviour as we have Brush Select and Lasso Select to perform single and multiple select, prevent double click behaviour clash with click select. 
* [ ] 2. Fix node does not move errors.

**Review by timlrx — APPROVED** [review]
The node positioning behaviour feels very intuitive to me now 👍

**Pull request merged**
